# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_objectives_list <- function(x) {
    invisible(.Call('RcppRP_test_objectives_list', PACKAGE = 'RcppRP', x))
}

rcpp_constrained_objective <- function(weights, args_list, objective, penalty = 10000) {
    .Call('RcppRP_rcpp_constrained_objective', PACKAGE = 'RcppRP', weights, args_list, objective, penalty)
}

rcpp_rp_optimize <- function(rp, args_list, objective) {
    .Call('RcppRP_rcpp_rp_optimize', PACKAGE = 'RcppRP', rp, args_list, objective)
}

rcpp_constrained_objective_v2 <- function(weights, objectives_list, args_list, penalty = 10000) {
    .Call('RcppRP_rcpp_constrained_objective_v2', PACKAGE = 'RcppRP', weights, objectives_list, args_list, penalty)
}

rcpp_rp_optimize_v2 <- function(rp, objectives_list, args_list) {
    .Call('RcppRP_rcpp_rp_optimize_v2', PACKAGE = 'RcppRP', rp, objectives_list, args_list)
}

rcpp_hello_world <- function() {
    .Call('RcppRP_rcpp_hello_world', PACKAGE = 'RcppRP')
}

rcpp_rp_sample <- function(init_weights, weight_seq, min_sum, max_sum, min_box, max_box, max_permutations) {
    .Call('RcppRP_rcpp_rp_sample', PACKAGE = 'RcppRP', init_weights, weight_seq, min_sum, max_sum, min_box, max_box, max_permutations)
}

rcpp_rp_unif <- function(init_weights, min_sum, max_sum, min_box, max_box, max_permutations) {
    .Call('RcppRP_rcpp_rp_unif', PACKAGE = 'RcppRP', init_weights, min_sum, max_sum, min_box, max_box, max_permutations)
}

rcpp_random_portfolios_sample <- function(n_portfolios, init_weights, weight_seq, min_sum, max_sum, min_box, max_box, max_permutations) {
    .Call('RcppRP_rcpp_random_portfolios_sample', PACKAGE = 'RcppRP', n_portfolios, init_weights, weight_seq, min_sum, max_sum, min_box, max_box, max_permutations)
}

rcpp_random_portfolios_unif <- function(n_portfolios, init_weights, min_sum, max_sum, min_box, max_box, max_permutations) {
    .Call('RcppRP_rcpp_random_portfolios_unif', PACKAGE = 'RcppRP', n_portfolios, init_weights, min_sum, max_sum, min_box, max_box, max_permutations)
}

